import { ArrowRight, Banknote, CircleDollarSign, Plus, TrendingUp, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'wouter'
import { PageHeader } from '../components/PageHeader'
import { ErrorBlock, LoadingBlock } from '../components/State'
import { formatDate, formatMoney, statusLabel, statusTone } from '../lib/expenses'
import { errorMessage } from '../lib/errors'
import { loadExpenses, loadProjectOverview } from '../lib/queries'
import type { Expense, ProjectCostOverview } from '../types/domain'

export function DashboardPage(){const [projects,setProjects]=useState<ProjectCostOverview[]>([]);const [expenses,setExpenses]=useState<Expense[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const refresh=()=>{setLoading(true);setError('');Promise.all([loadProjectOverview(),loadExpenses()]).then(([p,e])=>{setProjects(p);setExpenses(e.slice(0,6))}).catch((e)=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(refresh,[])
  const totals=useMemo(()=>projects.reduce((a,p)=>({contract:a.contract+p.current_contract_amount,committed:a.committed+p.committed_expenses,paid:a.paid+p.paid_expenses,profit:a.profit+p.estimated_gross_profit}),{contract:0,committed:0,paid:0,profit:0}),[projects])
  if(loading)return <LoadingBlock label="Mengira kedudukan semua projek..."/>;if(error)return <ErrorBlock message={error} retry={refresh}/>
  return <><PageHeader eyebrow="Dashboard expenses" title="Kos sebenar projek" description="Nilai kontrak datang terus daripada Contractor Suite. Expenses pula dikira apabila direkod atau dibayar." action={<Link href="/expenses/baru" className="btn-primary"><Plus className="h-4 w-4"/>Tambah expenses</Link>}/>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Nilai kontrak" value={formatMoney(totals.contract)} tone="slate"/><Metric icon={WalletCards} label="Jumlah expenses" value={formatMoney(totals.committed)} tone="amber"/><Metric icon={Banknote} label="Tunai dibayar" value={formatMoney(totals.paid)} tone="rose"/><Metric icon={TrendingUp} label="Anggaran untung kasar" value={formatMoney(totals.profit)} tone="emerald"/></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div><div className="section-title"><div><h2>Prestasi projek</h2><p>Kontrak ditolak semua komitmen expenses.</p></div><Link href="/projek">Lihat semua <ArrowRight className="h-4 w-4"/></Link></div><div className="space-y-3">{projects.slice(0,5).map((p)=>{const pct=p.current_contract_amount?Math.min(100,p.committed_expenses/p.current_contract_amount*100):0;return <article key={p.project_id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-emerald-700">{p.project_no}</p><h3 className="mt-1 font-black">{p.project_name}</h3><p className="mt-1 text-xs text-slate-500">{p.client_name}</p></div><p className="text-right text-sm font-black text-emerald-700">{formatMoney(p.estimated_gross_profit)}<span className="block text-[11px] font-semibold text-slate-400">anggaran untung</span></p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-400" style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between text-xs font-semibold text-slate-500"><span>Kos {formatMoney(p.committed_expenses)}</span><span>{pct.toFixed(1)}% kontrak</span></div></article>})}{!projects.length&&<p className="card p-6 text-sm text-slate-500">Belum ada projek daripada Contractor Suite.</p>}</div></div>
      <div><div className="section-title"><div><h2>Expenses terkini</h2><p>Rekod terbaru semua projek.</p></div><Link href="/expenses">Semua <ArrowRight className="h-4 w-4"/></Link></div><div className="card divide-y divide-slate-100 overflow-hidden">{expenses.map((e)=><Link key={e.id} href={`/expenses/${e.id}`} className="block p-4 transition hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black">{e.description}</p><p className="mt-1 text-xs text-slate-500">{formatDate(e.expense_date)}</p></div><div className="text-right"><p className="text-sm font-black">{formatMoney(e.total_amount)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-1 text-[10px] font-black ${statusTone(e.status)}`}>{statusLabel(e.status)}</span></div></div></Link>)}{!expenses.length&&<p className="p-6 text-sm text-slate-500">Belum ada expenses.</p>}</div></div></section>
  </>}

function Metric({icon:Icon,label,value,tone}:{icon:typeof CircleDollarSign;label:string;value:string;tone:'slate'|'amber'|'rose'|'emerald'}){const colors={slate:'bg-slate-950 text-white',amber:'bg-amber-50 text-amber-800',rose:'bg-rose-50 text-rose-800',emerald:'bg-emerald-600 text-white'};return <article className={`rounded-2xl p-5 ${colors[tone]}`}><Icon className="h-5 w-5 opacity-70"/><p className="mt-5 text-xs font-black uppercase tracking-[.12em] opacity-70">{label}</p><p className="mt-1 text-xl font-black">{value}</p></article>}
