import { Filter, Plus, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'wouter'
import { PageHeader } from '../components/PageHeader'
import { EmptyBlock, ErrorBlock, LoadingBlock } from '../components/State'
import { categoryLabel, formatDate, formatMoney, statusLabel, statusTone } from '../lib/expenses'
import { errorMessage } from '../lib/errors'
import { loadExpenses, loadProjects } from '../lib/queries'
import type { Expense, ExpenseStatus, Project } from '../types/domain'

export function ExpenseListPage(){const [expenses,setExpenses]=useState<Expense[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [search,setSearch]=useState('');const [projectId,setProjectId]=useState(()=>new URLSearchParams(window.location.search).get('project')??'');const [status,setStatus]=useState<''|ExpenseStatus>('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const refresh=()=>{setLoading(true);Promise.all([loadExpenses(),loadProjects()]).then(([e,p])=>{setExpenses(e);setProjects(p)}).catch((e)=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(refresh,[])
  const projectMap=useMemo(()=>new Map(projects.map((p)=>[p.id,p])),[projects]);const shown=useMemo(()=>expenses.filter((e)=>(!projectId||e.project_id===Number(projectId))&&(!status||e.status===status)&&(!search.trim()||`${e.description} ${projectMap.get(e.project_id)?.project_name??''}`.toLowerCase().includes(search.toLowerCase()))),[expenses,projectId,status,search,projectMap]);
  return <><PageHeader eyebrow="Rekod projek" title="Semua expenses" description="Cari mengikut projek, status bayaran atau keterangan." action={<Link href="/expenses/baru" className="btn-primary"><Plus className="h-4 w-4"/>Tambah</Link>}/><div className="card mb-5 grid gap-3 p-4 md:grid-cols-[1fr_220px_190px]"><label className="relative"><Search className="field-icon"/><input className="field-control pl-11" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Cari expenses..."/></label><label className="relative"><Filter className="field-icon"/><select className="field-control pl-11" value={projectId} onChange={(e)=>setProjectId(e.target.value)}><option value="">Semua projek</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.project_no} · {p.project_name}</option>)}</select></label><select className="field-control" value={status} onChange={(e)=>setStatus(e.target.value as ''|ExpenseStatus)}><option value="">Semua status</option><option value="unpaid">Belum bayar</option><option value="partially_paid">Bayar sebahagian</option><option value="paid">Selesai</option></select></div>
    {loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={refresh}/>:!shown.length?<EmptyBlock title="Tiada expenses ditemui" description="Ubah tapisan atau tambah rekod baharu."/>:<div className="space-y-3">{shown.map((e)=>{const p=projectMap.get(e.project_id);return <Link key={e.id} href={`/expenses/${e.id}`} className="card block p-4 transition hover:border-emerald-300 sm:p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black text-emerald-700">{p?.project_no}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusTone(e.status)}`}>{statusLabel(e.status)}</span></div><h2 className="mt-2 truncate font-black">{e.description}</h2><p className="mt-1 text-xs text-slate-500">{p?.project_name} · {categoryLabel(e.category)} · {formatDate(e.expense_date)}</p></div><div className="shrink-0 text-right"><p className="font-black">{formatMoney(e.total_amount)}</p>{e.balance_amount>0&&<p className="mt-1 text-xs font-semibold text-rose-600">Baki {formatMoney(e.balance_amount)}</p>}</div></div></Link>})}</div>}
  </>}
