import { ArrowLeft, Camera, Plus, Save, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useLocation } from 'wouter'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/PageHeader'
import { ErrorBlock, LoadingBlock } from '../components/State'
import { expenseCategories, expenseItemsTotal, formatMoney, paymentMethods, safeFileName, validateExpense } from '../lib/expenses'
import { errorMessage } from '../lib/errors'
import { loadCompany, loadProjects, loadSuppliers, normalizeExpense } from '../lib/queries'
import { supabase } from '../lib/supabase'
import type { Company, DraftExpenseItem, ExpenseCategory, PaymentMethod, Project, Supplier } from '../types/domain'

const blankItem=():DraftExpenseItem=>({description:'',quantity:'1',unit:'unit',unit_price:''})
const today=()=>new Date().toISOString().slice(0,10)

export function ExpenseFormPage(){const {user}=useAuth();const [,navigate]=useLocation();const [company,setCompany]=useState<Company|null>(null);const [projects,setProjects]=useState<Project[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [projectId,setProjectId]=useState('');const [date,setDate]=useState(today());const [category,setCategory]=useState<ExpenseCategory>('materials');const [description,setDescription]=useState('');const [supplierId,setSupplierId]=useState('');const [notes,setNotes]=useState('');const [items,setItems]=useState<DraftExpenseItem[]>([blankItem()]);const [payment,setPayment]=useState('');const [method,setMethod]=useState<PaymentMethod>('bank_transfer');const [reference,setReference]=useState('');const [receipt,setReceipt]=useState<File|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{Promise.all([loadCompany(),loadProjects(),loadSuppliers(true)]).then(([c,p,s])=>{setCompany(c);setProjects(p);setSuppliers(s);const firstProject=p[0];if(firstProject)setProjectId(String(firstProject.id))}).catch((e)=>setError(errorMessage(e))).finally(()=>setLoading(false))},[]);const total=useMemo(()=>expenseItemsTotal(items),[items]);
  function updateItem(index:number,key:keyof DraftExpenseItem,value:string){setItems((rows)=>rows.map((row,i)=>i===index?{...row,[key]:value}:row))}
  async function submit(event:FormEvent){event.preventDefault();if(!supabase||!company||!user)return;const validation=validateExpense(items,description,Number(payment||0));if(validation){setError(validation);return}if(!projectId){setError('Pilih projek.');return}setSaving(true);setError('');let uploadedPath='';try{const {data,error:rpcError}=await supabase.rpc('create_project_expense',{p_project_id:Number(projectId),p_expense_date:date,p_category:category,p_description:description.trim(),p_supplier_id:supplierId?Number(supplierId):null,p_notes:notes,p_items:items.map((item)=>({description:item.description.trim(),quantity:Number(item.quantity),unit:item.unit.trim()||'unit',unit_price:Number(item.unit_price)})),p_initial_payment:Number(payment||0),p_payment_method:Number(payment||0)>0?method:null,p_reference_no:reference||null});if(rpcError)throw rpcError;const expense=normalizeExpense(data as Record<string,unknown>);
      if(receipt){uploadedPath=`${user.id}/${projectId}/${crypto.randomUUID()}-${safeFileName(receipt.name)}`;const {error:uploadError}=await supabase.storage.from('expense-receipts').upload(uploadedPath,receipt,{contentType:receipt.type,upsert:false});if(uploadError)throw uploadError;const {error:attachmentError}=await supabase.from('project_expense_attachments').insert({expense_id:expense.id,project_id:expense.project_id,company_id:expense.company_id,owner_user_id:user.id,storage_path:uploadedPath,file_name:receipt.name,mime_type:receipt.type,file_size:receipt.size});if(attachmentError){await supabase.storage.from('expense-receipts').remove([uploadedPath]);throw attachmentError}}
      navigate(`/expenses/${expense.id}`,{replace:true})
    }catch(e){if(uploadedPath)await supabase.storage.from('expense-receipts').remove([uploadedPath]);setError(errorMessage(e))}finally{setSaving(false)}}
  if(loading)return <LoadingBlock label="Menyediakan borang expenses..."/>;return <><PageHeader eyebrow="Rekod baharu" title="Tambah expenses" description="Masukkan satu atau beberapa item dalam pembelian yang sama." action={<Link href="/expenses" className="btn-secondary"><ArrowLeft className="h-4 w-4"/>Kembali</Link>}/>{error&&<div className="mb-5"><ErrorBlock message={error}/></div>}<form onSubmit={submit} className="space-y-5"><section className="card grid gap-4 p-5 md:grid-cols-2"><h2 className="md:col-span-2 text-lg font-black">Maklumat utama</h2><label><span className="field-label">Projek</span><select className="field-control" required value={projectId} onChange={(e)=>setProjectId(e.target.value)}><option value="">Pilih projek</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.project_no} · {p.project_name}</option>)}</select></label><label><span className="field-label">Tarikh expenses</span><input type="date" className="field-control" required value={date} onChange={(e)=>setDate(e.target.value)}/></label><label><span className="field-label">Kategori</span><select className="field-control" value={category} onChange={(e)=>setCategory(e.target.value as ExpenseCategory)}>{expenseCategories.map((c)=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><label><span className="field-label">Pembekal</span><select className="field-control" value={supplierId} onChange={(e)=>setSupplierId(e.target.value)}><option value="">Tidak dinyatakan</option>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="md:col-span-2"><span className="field-label">Keterangan</span><input className="field-control" required value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Contoh: Belian simen dan pasir kasar"/></label></section>
    <section className="card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Pecahan item</h2><p className="mt-1 text-xs text-slate-500">Jumlah dikira automatik.</p></div><button type="button" className="btn-secondary" onClick={()=>setItems((rows)=>[...rows,blankItem()])}><Plus className="h-4 w-4"/>Item</button></div><div className="mt-5 space-y-4">{items.map((item,index)=><div key={index} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Item {index+1}</p>{items.length>1&&<button type="button" onClick={()=>setItems((rows)=>rows.filter((_,i)=>i!==index))} className="grid h-9 w-9 place-items-center rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_110px_110px_150px]"><input className="field-control" value={item.description} onChange={(e)=>updateItem(index,'description',e.target.value)} placeholder="Nama bahan / perkhidmatan" required/><input className="field-control" type="number" min="0.001" step="0.001" value={item.quantity} onChange={(e)=>updateItem(index,'quantity',e.target.value)} placeholder="Kuantiti" required/><input className="field-control" value={item.unit} onChange={(e)=>updateItem(index,'unit',e.target.value)} placeholder="Unit"/><input className="field-control" type="number" min="0" step="0.01" value={item.unit_price} onChange={(e)=>updateItem(index,'unit_price',e.target.value)} placeholder="Harga seunit" required/></div><p className="mt-3 text-right text-sm font-black">{formatMoney(Number(item.quantity||0)*Number(item.unit_price||0))}</p></div>)}</div><div className="mt-5 flex items-center justify-between rounded-2xl bg-slate-950 p-5 text-white"><span className="text-sm font-bold text-slate-300">Jumlah expenses</span><strong className="text-2xl font-black text-emerald-300">{formatMoney(total)}</strong></div></section>
    <section className="card grid gap-4 p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-black">Bayaran & bukti</h2><p className="mt-1 text-xs text-slate-500">Biarkan RM0 jika belum dibayar.</p></div><label><span className="field-label">Amaun dibayar sekarang</span><input className="field-control" type="number" min="0" max={total} step="0.01" value={payment} onChange={(e)=>setPayment(e.target.value)} placeholder="0.00"/></label><label><span className="field-label">Kaedah bayaran</span><select className="field-control" value={method} onChange={(e)=>setMethod(e.target.value as PaymentMethod)} disabled={!Number(payment)}>{paymentMethods.map((m)=><option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label><span className="field-label">No. rujukan</span><input className="field-control" value={reference} onChange={(e)=>setReference(e.target.value)} disabled={!Number(payment)} placeholder="Opsyenal"/></label><label><span className="field-label">Resit / invois pembekal</span><span className="flex min-h-12 items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-white px-4"><Camera className="h-5 w-5 text-emerald-600"/><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(e)=>setReceipt(e.target.files?.[0]??null)} className="min-w-0 text-sm"/></span></label><label className="md:col-span-2"><span className="field-label">Catatan</span><textarea className="field-control" value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="Opsyenal"/></label></section><div className="sticky bottom-20 z-10 flex justify-end rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur lg:bottom-4"><button className="btn-primary min-w-44" disabled={saving}><Save className="h-4 w-4"/>{saving?'Menyimpan...':'Simpan expenses'}</button></div></form></>}
