import { ArrowLeft, Banknote, FileText, Plus, Receipt, Store, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link } from 'wouter'
import { PageHeader } from '../components/PageHeader'
import { ErrorBlock, LoadingBlock } from '../components/State'
import { categoryLabel, formatDate, formatMoney, paymentMethods, statusLabel, statusTone } from '../lib/expenses'
import { errorMessage } from '../lib/errors'
import { normalizeExpense } from '../lib/queries'
import { supabase } from '../lib/supabase'
import type { Expense, ExpenseAttachment, ExpenseItem, ExpensePayment, PaymentMethod, Project, Supplier } from '../types/domain'

type ReceiptLink=ExpenseAttachment&{url:string}
export function ExpenseDetailPage({expenseId}:{expenseId:string}){const id=Number(expenseId);const [expense,setExpense]=useState<Expense|null>(null);const [project,setProject]=useState<Project|null>(null);const [supplier,setSupplier]=useState<Supplier|null>(null);const [items,setItems]=useState<ExpenseItem[]>([]);const [payments,setPayments]=useState<ExpensePayment[]>([]);const [attachments,setAttachments]=useState<ReceiptLink[]>([]);const [payOpen,setPayOpen]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  async function refresh(){if(!supabase)return;setLoading(true);setError('');try{const {data:expenseData,error:expenseError}=await supabase.from('project_expenses').select('*').eq('id',id).single();if(expenseError)throw expenseError;const row=normalizeExpense(expenseData as Record<string,unknown>);setExpense(row);const [projectResult,itemResult,paymentResult,attachmentResult,supplierResult]=await Promise.all([supabase.from('projects').select('id,company_id,owner_user_id,project_no,project_name,client_name,status,current_contract_amount').eq('id',row.project_id).single(),supabase.from('project_expense_items').select('*').eq('expense_id',id).order('sort_order'),supabase.from('project_expense_payments').select('*').eq('expense_id',id).order('payment_date',{ascending:false}).order('id',{ascending:false}),supabase.from('project_expense_attachments').select('*').eq('expense_id',id).order('id'),row.supplier_id?supabase.from('expense_suppliers').select('*').eq('id',row.supplier_id).single():Promise.resolve({data:null,error:null})]);for(const result of [projectResult,itemResult,paymentResult,attachmentResult,supplierResult])if(result.error)throw result.error;if(!projectResult.data)throw new Error('Projek bagi expenses ini tidak ditemui.');setProject({...projectResult.data,current_contract_amount:Number(projectResult.data.current_contract_amount)} as Project);setItems((itemResult.data??[]).map((r)=>({...r,quantity:Number(r.quantity),unit_price:Number(r.unit_price),amount:Number(r.amount)})) as ExpenseItem[]);setPayments((paymentResult.data??[]).map((r)=>({...r,amount:Number(r.amount)})) as ExpensePayment[]);setSupplier(supplierResult.data as Supplier|null);const links:ReceiptLink[]=[];for(const file of (attachmentResult.data??[]) as ExpenseAttachment[]){const {data}=await supabase.storage.from('expense-receipts').createSignedUrl(file.storage_path,3600);links.push({...file,url:data?.signedUrl??''})}setAttachments(links)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}useEffect(()=>{void refresh()},[id]);
  async function addPayment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!expense)return;const form=new FormData(event.currentTarget);setSaving(true);setError('');try{const {error:e}=await supabase.rpc('record_project_expense_payment',{p_expense_id:expense.id,p_payment_date:String(form.get('payment_date')),p_amount:Number(form.get('amount')),p_payment_method:String(form.get('payment_method')),p_reference_no:String(form.get('reference_no')||'')||null,p_notes:String(form.get('notes')||'')});if(e)throw e;setPayOpen(false);await refresh()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
  const totalItems=useMemo(()=>items.reduce((s,i)=>s+i.amount,0),[items]);if(loading)return <LoadingBlock label="Memuatkan butiran expenses..."/>;if(error&&!expense)return <ErrorBlock message={error} retry={()=>void refresh()}/>;if(!expense)return null;
  return <><PageHeader eyebrow={project?.project_no} title={expense.description} description={`${project?.project_name??''} · ${formatDate(expense.expense_date)}`} action={<Link href="/expenses" className="btn-secondary"><ArrowLeft className="h-4 w-4"/>Kembali</Link>}/>{error&&<div className="mb-5"><ErrorBlock message={error}/></div>}<section className="grid gap-3 sm:grid-cols-3"><Summary icon={WalletCards} label="Jumlah" value={formatMoney(expense.total_amount)}/><Summary icon={Banknote} label="Sudah dibayar" value={formatMoney(expense.paid_amount)} accent/><Summary icon={Receipt} label="Baki" value={formatMoney(expense.balance_amount)} danger={expense.balance_amount>0}/></section><div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><section className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${statusTone(expense.status)}`}>{statusLabel(expense.status)}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-600">{categoryLabel(expense.category)}</span>{expense.source_type!=='manual'&&<span className="rounded-full bg-violet-50 px-2.5 py-1 text-[11px] font-black text-violet-700">Daripada Workforce</span>}</div><h2 className="mt-4 text-lg font-black">Pecahan item</h2></div><div className="divide-y divide-slate-100">{items.map((item)=><div key={item.id} className="grid grid-cols-[1fr_auto] gap-4 p-5"><div><p className="font-bold">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.quantity} {item.unit} × {formatMoney(item.unit_price)}</p></div><p className="font-black">{formatMoney(item.amount)}</p></div>)}</div><div className="flex justify-between bg-slate-950 p-5 text-white"><span className="font-bold text-slate-300">Jumlah item</span><strong className="text-lg text-emerald-300">{formatMoney(totalItems)}</strong></div></section><section className="card p-5"><h2 className="text-lg font-black">Maklumat tambahan</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Pembekal" value={supplier?.name??'Tidak dinyatakan'} icon={Store}/><Info label="Sumber rekod" value={expense.source_type==='manual'?'Expenses manual':'MRPI Workforce'} icon={FileText}/><div className="sm:col-span-2"><dt className="text-xs font-black uppercase tracking-wider text-slate-400">Catatan</dt><dd className="mt-1 whitespace-pre-line font-semibold text-slate-700">{expense.notes||'Tiada catatan.'}</dd></div></dl></section></div>
    <div className="space-y-6"><section className="card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Bayaran</h2><p className="mt-1 text-xs text-slate-500">Rekod bayaran kepada pembekal.</p></div>{expense.balance_amount>0&&<button className="btn-primary" onClick={()=>setPayOpen((v)=>!v)}><Plus className="h-4 w-4"/>Bayaran</button>}</div>{payOpen&&<form onSubmit={addPayment} className="mt-4 space-y-3 rounded-2xl bg-slate-50 p-4"><label><span className="field-label">Tarikh</span><input name="payment_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className="field-control"/></label><label><span className="field-label">Amaun</span><input name="amount" type="number" min="0.01" max={expense.balance_amount} step="0.01" required defaultValue={expense.balance_amount} className="field-control"/></label><label><span className="field-label">Kaedah</span><select name="payment_method" className="field-control" defaultValue={'bank_transfer' satisfies PaymentMethod}>{paymentMethods.map((m)=><option value={m.value} key={m.value}>{m.label}</option>)}</select></label><label><span className="field-label">No. rujukan</span><input name="reference_no" className="field-control"/></label><label><span className="field-label">Catatan</span><textarea name="notes" className="field-control"/></label><button disabled={saving} className="btn-primary w-full">{saving?'Menyimpan...':'Simpan bayaran'}</button></form>}<div className="mt-4 space-y-3">{payments.map((p)=><div key={p.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="text-sm font-black">{formatDate(p.payment_date)}</p><p className="mt-1 text-xs text-slate-500">{paymentMethods.find((m)=>m.value===p.payment_method)?.label}{p.reference_no?` · ${p.reference_no}`:''}</p></div><p className="font-black text-emerald-700">{formatMoney(p.amount)}</p></div></div>)}{!payments.length&&<p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Belum ada bayaran.</p>}</div></section><section className="card p-5"><h2 className="text-lg font-black">Resit & dokumen</h2><div className="mt-4 space-y-2">{attachments.map((file)=><a key={file.id} href={file.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold hover:border-emerald-300"><FileText className="h-5 w-5 text-emerald-600"/><span className="min-w-0 truncate">{file.file_name}</span></a>)}{!attachments.length&&<p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Tiada resit dilampirkan.</p>}</div></section></div></div></>}
function Summary({icon:Icon,label,value,accent,danger}:{icon:typeof WalletCards;label:string;value:string;accent?:boolean;danger?:boolean}){return <article className="card p-5"><Icon className={`h-5 w-5 ${danger?'text-rose-500':accent?'text-emerald-600':'text-slate-400'}`}/><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 text-xl font-black ${danger?'text-rose-700':accent?'text-emerald-700':''}`}>{value}</p></article>}
function Info({label,value,icon:Icon}:{label:string;value:string;icon:typeof Store}){return <div><dt className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-400"><Icon className="h-4 w-4"/>{label}</dt><dd className="mt-1 font-semibold text-slate-700">{value}</dd></div>}
