import { ArrowRight, TrendingDown, TrendingUp, Wallet } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'wouter'
import { PageHeader } from '../components/PageHeader'
import { EmptyBlock, ErrorBlock, LoadingBlock } from '../components/State'
import { formatMoney } from '../lib/expenses'
import { errorMessage } from '../lib/errors'
import { loadProjectOverview } from '../lib/queries'
import type { ProjectCostOverview } from '../types/domain'

export function ProjectListPage(){const [rows,setRows]=useState<ProjectCostOverview[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const refresh=()=>{setLoading(true);loadProjectOverview().then(setRows).catch((e)=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(refresh,[]);return <><PageHeader eyebrow="Tally Contractor Suite" title="Kos mengikut projek" description="Nama, pelanggan dan nilai kontrak dibaca terus daripada sistem utama."/>{loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={refresh}/>:!rows.length?<EmptyBlock title="Belum ada projek" description="Terima sebutharga dalam Contractor Suite untuk menghasilkan projek."/>:<div className="grid gap-4 lg:grid-cols-2">{rows.map((p)=>{const margin=p.current_contract_amount?p.estimated_gross_profit/p.current_contract_amount*100:0;return <article key={p.project_id} className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><p className="text-xs font-black text-emerald-700">{p.project_no}</p><h2 className="mt-1 text-lg font-black">{p.project_name}</h2><p className="mt-1 text-sm text-slate-500">{p.client_name}</p></div><div className="grid grid-cols-2 gap-px bg-slate-100"><Fact label="Kontrak semasa" value={formatMoney(p.current_contract_amount)} icon={Wallet}/><Fact label="Expenses" value={formatMoney(p.committed_expenses)} icon={TrendingDown}/><Fact label="Tunai diterima" value={formatMoney(p.customer_received)} icon={Wallet}/><Fact label="Untung anggaran" value={formatMoney(p.estimated_gross_profit)} icon={TrendingUp} accent/></div><div className="flex items-center justify-between p-4"><p className={`text-xs font-black ${margin>=0?'text-emerald-700':'text-rose-700'}`}>Margin anggaran {margin.toFixed(1)}%</p><Link href={`/expenses?project=${p.project_id}`} className="inline-flex items-center gap-1 text-xs font-black text-slate-700">Expenses <ArrowRight className="h-4 w-4"/></Link></div></article>})}</div>}</>}
function Fact({label,value,icon:Icon,accent}:{label:string;value:string;icon:typeof Wallet;accent?:boolean}){return <div className="bg-white p-4"><Icon className={`h-4 w-4 ${accent?'text-emerald-600':'text-slate-400'}`}/><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 text-sm font-black ${accent?'text-emerald-700':''}`}>{value}</p></div>}
