import { Pencil, Plus, Store } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { PageHeader } from '../components/PageHeader'
import { EmptyBlock, ErrorBlock, LoadingBlock } from '../components/State'
import { useAuth } from '../auth/AuthProvider'
import { errorMessage } from '../lib/errors'
import { loadCompany, loadSuppliers } from '../lib/queries'
import { supabase } from '../lib/supabase'
import type { Company, Supplier } from '../types/domain'

export function SupplierPage(){const [company,setCompany]=useState<Company|null>(null);const [rows,setRows]=useState<Supplier[]>([]);const [editing,setEditing]=useState<Supplier|null>(null);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const {user}=useAuth();const refresh=()=>{setLoading(true);Promise.all([loadCompany(),loadSuppliers()]).then(([c,s])=>{setCompany(c);setRows(s)}).catch((e)=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(refresh,[])
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!company||!user)return;const form=new FormData(event.currentTarget);const payload={name:String(form.get('name')||'').trim(),phone:String(form.get('phone')||'').trim()||null,notes:String(form.get('notes')||''),is_active:form.get('is_active')==='on'};try{setError('');if(editing){const {error:e}=await supabase.from('expense_suppliers').update(payload).eq('id',editing.id);if(e)throw e}else{const {error:e}=await supabase.from('expense_suppliers').insert({...payload,company_id:company.id,owner_user_id:user.id});if(e)throw e}setOpen(false);setEditing(null);refresh()}catch(e){setError(errorMessage(e))}}
  return <><PageHeader eyebrow="Direktori ringkas" title="Pembekal" description="Simpan nama kedai atau pembekal supaya rekod belian lebih mudah dicari." action={<button className="btn-primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus className="h-4 w-4"/>Tambah</button>}/>{error&&<div className="mb-4"><ErrorBlock message={error}/></div>}{open&&<form onSubmit={save} className="card mb-5 grid gap-4 p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="font-black">{editing?'Kemaskini pembekal':'Pembekal baharu'}</h2></div><label><span className="field-label">Nama</span><input name="name" className="field-control" required defaultValue={editing?.name}/></label><label><span className="field-label">Telefon</span><input name="phone" className="field-control" inputMode="tel" defaultValue={editing?.phone??''}/></label><label className="md:col-span-2"><span className="field-label">Catatan</span><textarea name="notes" className="field-control" defaultValue={editing?.notes}/></label><label className="flex items-center gap-3 text-sm font-bold"><input name="is_active" type="checkbox" defaultChecked={editing?.is_active??true} className="h-5 w-5 accent-emerald-600"/>Pembekal aktif</label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Batal</button><button className="btn-primary">Simpan</button></div></form>}{loading?<LoadingBlock/>:!rows.length?<EmptyBlock title="Belum ada pembekal" description="Tambah pembekal pertama apabila membuat belian."/>:<div className="grid gap-3 md:grid-cols-2">{rows.map((s)=><article key={s.id} className="card flex items-start gap-4 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Store className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h2 className="font-black">{s.name}</h2><p className="mt-1 text-sm text-slate-500">{s.phone||'Tiada nombor telefon'}</p></div><button onClick={()=>{setEditing(s);setOpen(true)}} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button></div>{s.notes&&<p className="mt-3 text-xs leading-5 text-slate-500">{s.notes}</p>}{!s.is_active&&<span className="mt-3 inline-flex rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-500">Tidak aktif</span>}</div></article>)}</div>}</>}
