import { supabase } from './supabase'
import type { Company, Expense, Project, ProjectCostOverview, Supplier } from '../types/domain'

function configured() { if (!supabase) throw new Error('Supabase belum dikonfigurasi.'); return supabase }
export async function loadCompany() { const {data,error}=await configured().from('companies').select('id,owner_user_id,legal_name,trading_name').single();if(error)throw error;return data as Company }
export async function loadProjects() { const {data,error}=await configured().from('projects').select('id,company_id,owner_user_id,project_no,project_name,client_name,status,current_contract_amount').order('updated_at',{ascending:false});if(error)throw error;return (data??[]).map((row)=>({...row,current_contract_amount:Number(row.current_contract_amount)})) as Project[] }
export async function loadProjectOverview() { const {data,error}=await configured().from('project_cost_overview').select('*').order('project_no',{ascending:false});if(error)throw error;return (data??[]).map((row)=>({ ...row, id:Number(row.project_id), current_contract_amount:Number(row.current_contract_amount), committed_expenses:Number(row.committed_expenses), paid_expenses:Number(row.paid_expenses), outstanding_expenses:Number(row.outstanding_expenses), customer_received:Number(row.customer_received), estimated_gross_profit:Number(row.estimated_gross_profit), cash_position:Number(row.cash_position) })) as ProjectCostOverview[] }
export async function loadSuppliers(activeOnly=false) { let query=configured().from('expense_suppliers').select('*').order('name');if(activeOnly)query=query.eq('is_active',true);const {data,error}=await query;if(error)throw error;return (data??[]) as Supplier[] }
export async function loadExpenses(projectId?:number) { let query=configured().from('project_expenses').select('*').order('expense_date',{ascending:false}).order('id',{ascending:false});if(projectId)query=query.eq('project_id',projectId);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeExpense) }
export function normalizeExpense(row: Record<string,unknown>) { return {...row,total_amount:Number(row.total_amount),paid_amount:Number(row.paid_amount),balance_amount:Number(row.balance_amount)} as Expense }
