import { supabase } from './supabase'
import type { Attendance, Company, Project, WagePayment, Worker, WorkerAdvance, WorkerBalance } from '../types/domain'
function configured(){if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase}
export async function loadCompany(){const {data,error}=await configured().from('companies').select('id,owner_user_id,legal_name,trading_name').single();if(error)throw error;return data as Company}
export async function loadProjects(){const {data,error}=await configured().from('projects').select('id,company_id,owner_user_id,project_no,project_alias,project_name,client_name,status').order('updated_at',{ascending:false});if(error)throw error;return (data??[]).map((row)=>{const alias=typeof row.project_alias==='string'&&row.project_alias.trim()?row.project_alias.trim():null;return {...row,source_project_no:row.project_no,workforce_name:alias,project_no:alias||row.project_no} as Project})}
export async function loadWorkers(activeOnly=false){let query=configured().from('workers').select('*').order('name');if(activeOnly)query=query.eq('is_active',true);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeWorker)}
export async function loadWorker(workerId:number){const {data,error}=await configured().from('workers').select('*').eq('id',workerId).maybeSingle();if(error)throw error;return data?normalizeWorker(data):null}
export async function loadAttendance(date?:string){let query=configured().from('worker_attendance').select('*').order('attendance_date',{ascending:false}).order('id',{ascending:false});if(date)query=query.eq('attendance_date',date);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeAttendance)}
export async function loadWorkerAttendance(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_attendance').select('*').eq('worker_id',workerId).order('attendance_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('attendance_date',fromDate);if(toDate)query=query.lte('attendance_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeAttendance)}
export async function loadWorkerBalances(){const {data,error}=await configured().from('worker_balance_overview').select('*').order('name');if(error)throw error;return (data??[]).map((row)=>({...row,worker_id:Number(row.worker_id),default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate),unpaid_wages:Number(row.unpaid_wages),unapplied_advances:Number(row.unapplied_advances),estimated_balance:Number(row.estimated_balance)})) as WorkerBalance[]}
export async function loadWorkerBalance(workerId:number){const {data,error}=await configured().from('worker_balance_overview').select('*').eq('worker_id',workerId).maybeSingle();if(error)throw error;return data?normalizeWorkerBalance(data):null}
export async function loadAdvances(unappliedOnly=false){let query=configured().from('worker_advances').select('*').order('advance_date',{ascending:false}).order('id',{ascending:false});if(unappliedOnly)query=query.is('applied_wage_payment_id',null).is('applied_wage_batch_id',null);const {data,error}=await query;if(error)throw error;return (data??[]).map((row)=>({...row,worker_id:Number(row.worker_id),project_id:Number(row.project_id),amount:Number(row.amount)})) as WorkerAdvance[]}
export async function loadWorkerAdvances(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_advances').select('*').eq('worker_id',workerId).eq('advance_scope','worker').order('advance_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('advance_date',fromDate);if(toDate)query=query.lte('advance_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map((row)=>({...row,worker_id:Number(row.worker_id),project_id:Number(row.project_id),amount:Number(row.amount)})) as WorkerAdvance[]}
export async function loadWagePayments(){const {data,error}=await configured().from('worker_wage_payments').select('*').order('payment_date',{ascending:false}).order('id',{ascending:false});if(error)throw error;return (data??[]).map(normalizeWagePayment) as WagePayment[]}
export async function loadWorkerWagePayments(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_wage_payments').select('*').eq('worker_id',workerId).order('payment_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('payment_date',fromDate);if(toDate)query=query.lte('payment_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeWagePayment) as WagePayment[]}
export function normalizeWorker(row:Record<string,unknown>){return {...row,id:Number(row.id),company_id:Number(row.company_id),default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate),is_crew_leader:Boolean(row.is_crew_leader),crew_leader_id:row.crew_leader_id===null||row.crew_leader_id===undefined?null:Number(row.crew_leader_id)} as Worker}
export function normalizeAttendance(row:Record<string,unknown>){return {...row,id:Number(row.id),worker_id:Number(row.worker_id),project_id:row.project_id===null?null:Number(row.project_id),daily_rate_snapshot:Number(row.daily_rate_snapshot),overtime_hours:Number(row.overtime_hours),overtime_rate:Number(row.overtime_rate),wage_amount:Number(row.wage_amount),paid_wage_amount:Number(row.paid_wage_amount??0)} as Attendance}
export function normalizeWagePayment(row:Record<string,unknown>){return {...row,id:Number(row.id),worker_id:Number(row.worker_id),project_id:Number(row.project_id),gross_amount:Number(row.gross_amount),advance_deduction:Number(row.advance_deduction),crew_advance_deduction:Number(row.crew_advance_deduction??0),net_amount:Number(row.net_amount),recipient_worker_id:row.recipient_worker_id===null||row.recipient_worker_id===undefined?null:Number(row.recipient_worker_id),wage_batch_id:row.wage_batch_id===null||row.wage_batch_id===undefined?null:Number(row.wage_batch_id)} as WagePayment}
export function normalizeWorkerBalance(row:Record<string,unknown>){return {...row,worker_id:Number(row.worker_id),default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate),unpaid_wages:Number(row.unpaid_wages),unapplied_advances:Number(row.unapplied_advances),estimated_balance:Number(row.estimated_balance)} as WorkerBalance}
