import { supabase } from './supabase'
import type { Attendance, Company, Project, WagePayment, Worker, WorkerAdvance, WorkerBalance } from '../types/domain'
function configured(){if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase}
export async function loadCompany(){const {data,error}=await configured().from('companies').select('id,owner_user_id,legal_name,trading_name').single();if(error)throw error;return data as Company}
export async function loadProjects(){const client=configured();const [{data,error},{data:aliases,error:aliasError}]=await Promise.all([client.from('projects').select('id,company_id,owner_user_id,project_no,project_name,client_name,status').order('updated_at',{ascending:false}),client.from('workforce_project_aliases').select('project_id,display_name')]);if(error)throw error;if(aliasError)throw aliasError;const aliasMap=new Map((aliases??[]).map((row)=>[Number(row.project_id),String(row.display_name)]));return (data??[]).map((row)=>{const workforceName=aliasMap.get(Number(row.id))??null;return {...row,source_project_no:row.project_no,workforce_name:workforceName,project_no:workforceName||row.project_no} as Project})}
export async function saveProjectAlias(project:Project,displayName:string){const value=displayName.trim();if(!value)throw new Error('Nama projek Workforce tidak boleh kosong.');const {error}=await configured().from('workforce_project_aliases').upsert({project_id:project.id,company_id:project.company_id,owner_user_id:project.owner_user_id,display_name:value,updated_at:new Date().toISOString()},{onConflict:'project_id'});if(error)throw error}
export async function clearProjectAlias(projectId:number){const {error}=await configured().from('workforce_project_aliases').delete().eq('project_id',projectId);if(error)throw error}
export async function loadWorkers(activeOnly=false){let query=configured().from('workers').select('*').order('name');if(activeOnly)query=query.eq('is_active',true);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeWorker)}
export async function loadWorker(workerId:number){const {data,error}=await configured().from('workers').select('*').eq('id',workerId).maybeSingle();if(error)throw error;return data?normalizeWorker(data):null}
export async function loadAttendance(date?:string){let query=configured().from('worker_attendance').select('*').order('attendance_date',{ascending:false}).order('id',{ascending:false});if(date)query=query.eq('attendance_date',date);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeAttendance)}
export async function loadWorkerAttendance(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_attendance').select('*').eq('worker_id',workerId).order('attendance_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('attendance_date',fromDate);if(toDate)query=query.lte('attendance_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map(normalizeAttendance)}
export async function loadWorkerBalances(){const {data,error}=await configured().from('worker_balance_overview').select('*').order('name');if(error)throw error;return (data??[]).map((row)=>({...row,worker_id:Number(row.worker_id),default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate),unpaid_wages:Number(row.unpaid_wages),unapplied_advances:Number(row.unapplied_advances),estimated_balance:Number(row.estimated_balance)})) as WorkerBalance[]}
export async function loadWorkerBalance(workerId:number){const {data,error}=await configured().from('worker_balance_overview').select('*').eq('worker_id',workerId).maybeSingle();if(error)throw error;return data?normalizeWorkerBalance(data):null}
export async function loadAdvances(unappliedOnly=false){let query=configured().from('worker_advances').select('*').order('advance_date',{ascending:false}).order('id',{ascending:false});if(unappliedOnly)query=query.is('applied_wage_payment_id',null);const {data,error}=await query;if(error)throw error;return (data??[]).map((row)=>({...row,amount:Number(row.amount)})) as WorkerAdvance[]}
export async function loadWorkerAdvances(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_advances').select('*').eq('worker_id',workerId).order('advance_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('advance_date',fromDate);if(toDate)query=query.lte('advance_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map((row)=>({...row,amount:Number(row.amount)})) as WorkerAdvance[]}
export async function loadWagePayments(){const {data,error}=await configured().from('worker_wage_payments').select('*').order('payment_date',{ascending:false}).order('id',{ascending:false});if(error)throw error;return (data??[]).map((row)=>({...row,gross_amount:Number(row.gross_amount),advance_deduction:Number(row.advance_deduction),net_amount:Number(row.net_amount)})) as WagePayment[]}
export async function loadWorkerWagePayments(workerId:number,fromDate?:string,toDate?:string){let query=configured().from('worker_wage_payments').select('*').eq('worker_id',workerId).order('payment_date',{ascending:false}).order('id',{ascending:false});if(fromDate)query=query.gte('payment_date',fromDate);if(toDate)query=query.lte('payment_date',toDate);const {data,error}=await query;if(error)throw error;return (data??[]).map((row)=>({...row,gross_amount:Number(row.gross_amount),advance_deduction:Number(row.advance_deduction),net_amount:Number(row.net_amount)})) as WagePayment[]}
export function normalizeWorker(row:Record<string,unknown>){return {...row,default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate)} as Worker}
export function normalizeAttendance(row:Record<string,unknown>){return {...row,daily_rate_snapshot:Number(row.daily_rate_snapshot),overtime_hours:Number(row.overtime_hours),overtime_rate:Number(row.overtime_rate),wage_amount:Number(row.wage_amount),paid_wage_amount:Number(row.paid_wage_amount??0)} as Attendance}
export function normalizeWorkerBalance(row:Record<string,unknown>){return {...row,worker_id:Number(row.worker_id),default_daily_rate:row.default_daily_rate===null?null:Number(row.default_daily_rate),unpaid_wages:Number(row.unpaid_wages),unapplied_advances:Number(row.unapplied_advances),estimated_balance:Number(row.estimated_balance)} as WorkerBalance}
